# -*- coding: utf-8 -*-
"""Soporte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rzb-qvQax4WWOFpbRBQW_6BF7-D5ZcA2
"""

from google.colab import drive
drive.mount('/content/drive')

import os

ruta_dataset = '/content/drive/MyDrive/Facultad/Soporte/Proyecto_Reciclaje/dataset-resized'

# Le pedimos a Python que nos muestre qué carpetas hay adentro
categorias = os.listdir(ruta_dataset)
print("Las carpetas encontradas son:", categorias)

import tensorflow as tf

# Usamos la misma ruta que comprobaste que funciona
ruta_dataset = '/content/drive/MyDrive/Facultad/Soporte/Proyecto_Reciclaje/dataset-resized'

# Armamos la "cinta transportadora" para entrenar
dataset_entrenamiento = tf.keras.utils.image_dataset_from_directory(
    ruta_dataset,
    validation_split=0.2, # Separamos un 20% de las fotos para tomarle examen al modelo después
    subset="training",
    seed=123, # Una semilla para que la mezcla de fotos sea siempre igual
    image_size=(224, 224), # Achicamos todas las fotos a este tamaño estándar para que pesen menos
    batch_size=32 # Pasamos las fotos de a 32 a la vez
)

print("¡Cinta transportadora lista!")

import matplotlib.pyplot as plt

# 1. Armamos la cinta para el "examen" (validación) usando el 20% restante
dataset_validacion = tf.keras.utils.image_dataset_from_directory(
    ruta_dataset, # Sigue usando la variable que ya tenías guardada
    validation_split=0.2,
    subset="validation", # Acá cambiamos a validación
    seed=123,
    image_size=(224, 224),
    batch_size=32
)

# 2. Extraemos los nombres de las categorías que la IA leyó de las carpetas
nombres_clases = dataset_entrenamiento.class_names
print("\nLas categorías oficiales son:", nombres_clases)

# 3. Le decimos que nos muestre las primeras 9 fotos para ver si cargaron bien
plt.figure(figsize=(10, 10))
for imagenes, etiquetas in dataset_entrenamiento.take(1):
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    # Mostramos la imagen
    plt.imshow(imagenes[i].numpy().astype("uint8"))
    # Le ponemos de título a qué categoría pertenece
    plt.title(nombres_clases[etiquetas[i]])
    plt.axis("off")

import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Cargamos la herramienta de preprocesamiento específica de MobileNetV2
# Esto escala los píxeles de las fotos automáticamente al formato que el modelo espera
preprocesamiento = tf.keras.applications.mobilenet_v2.preprocess_input

# 2. Descargamos el modelo base MobileNetV2 entrenado con el dataset gigante 'imagenet'
# Le decimos 'include_top=False' para quitarle su clasificador de fábrica y poner el nuestro
modelo_base = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

# 3. ¡CRUCIAL! Congelamos el modelo base para que no borre lo que ya sabe de fábrica
modelo_base.trainable = False

# 4. Construimos la estructura definitiva uniendo las piezas como un Lego
entradas = tf.keras.Input(shape=(224, 224, 3))
x = preprocesamiento(entradas)
x = modelo_base(x, training=False) # Corre en modo inferencia
x = layers.GlobalAveragePooling2D()(x) # Aplana la información de la imagen
x = layers.Dropout(0.2)(x) # Apaga neuronas al azar para que no se estudie las fotos de memoria
salidas = layers.Dense(6, activation='softmax')(x) # 6 salidas con probabilidad para nuestras 6 clases

modelo_final = models.Model(entradas, salidas)

# 5. Compilamos el modelo indicando cómo medir los errores y qué optimizador usar
modelo_final.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

# Mostramos el mapa de la estructura en pantalla
modelo_final.summary()
print("\n¡Estructura de la Inteligencia Artificial creada con éxito!")

# 1. Definimos cuántas veces va a leer el dataset completo
epocas = 5

print("Arrancando el entrenamiento. ¡A transpirar esos procesadores!")

# 2. Entrenamos el modelo (el método .fit)
historial = modelo_final.fit(
    dataset_entrenamiento,               # Estudia con estas fotos
    validation_data=dataset_validacion,  # Rinde el examen con estas fotos
    epochs=epocas                        # Lo hace 5 veces
)

print("\n¡Entrenamiento terminado! Su IA acaba de aprender a clasificar basura.")

import numpy as np
import matplotlib.pyplot as plt

# Sacamos un lote de 32 fotos del examen
for imagenes_prueba, etiquetas_prueba in dataset_validacion.take(1):

    # ¡LA IA TRABAJANDO! Le pedimos que adivine qué hay en las fotos
    predicciones = modelo_final.predict(imagenes_prueba)

    # Preparamos la grilla visual de 9 fotos
    plt.figure(figsize=(10, 10))
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow(imagenes_prueba[i].numpy().astype("uint8"))

        # Averiguamos qué categoría eligió la IA y cuál era la verdadera
        indice_prediccion = np.argmax(predicciones[i])
        clase_predicha = nombres_clases[indice_prediccion]
        clase_real = nombres_clases[etiquetas_prueba[i]]

        # Pintamos el texto de verde si acertó, o rojo si le erró
        color = "green" if clase_predicha == clase_real else "red"

        plt.title(f"IA dice: {clase_predicha}\nReal: {clase_real}", color=color)
        plt.axis("off")

# 1. Elegimos la ruta en su Drive y le ponemos un nombre al archivo
# (Lo guardamos directo en la carpeta principal de su Drive para que lo encuentren fácil)
ruta_guardado = '/content/drive/MyDrive/modelo_trashnet_grupo6.keras'

# 2. Damos la orden de guardar el "cerebro" completo (estructura + lo que aprendió)
modelo_final.save(ruta_guardado)

print(f"¡Cerebro guardado con éxito!\nLo pueden encontrar en su Drive como: modelo_trashnet_grupo6.keras")

from google.colab import files
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 1. Se abre un botón para que elijan la foto desde su dispositivo
print("Hacé clic en 'Elegir archivos' y seleccioná la foto de tu celu:")
archivos_subidos = files.upload()

# 2. Procesamos la foto que acaban de subir
for nombre_archivo in archivos_subidos.keys():
    print(f"\nAnalizando el archivo: {nombre_archivo}...")

    # 3. Cargamos la foto y la achicamos a 224x224 (igual que hicimos con TrashNet)
    img_original = tf.keras.utils.load_img(nombre_archivo)
    img_redimensionada = tf.keras.utils.load_img(nombre_archivo, target_size=(224, 224))

    # 4. La convertimos en números (matriz) y le agregamos la dimensión de lote
    img_array = tf.keras.utils.img_to_array(img_redimensionada)
    img_array = tf.expand_dims(img_array, 0)

    # 5. ¡Momento de la verdad! La IA da su veredicto
    prediccion = modelo_final.predict(img_array)

    # Buscamos cuál es la clase con mayor puntaje
    indice_ganador = np.argmax(prediccion[0])
    clase_adivinada = nombres_clases[indice_ganador]

    # Calculamos el porcentaje de seguridad que tiene la máquina
    porcentaje_confianza = 100 * np.max(prediccion[0])

    # 6. Mostramos la foto original con el resultado arriba
    plt.figure(figsize=(6, 6))
    plt.imshow(img_original)
    plt.title(f"IA dice: {clase_adivinada.upper()}\nConfianza: {porcentaje_confianza:.2f}%", fontsize=14, color="blue")
    plt.axis("off")
    plt.show()

import tensorflow as tf

# Buscamos el archivo que guardamos ayer en tu Drive
ruta_guardado = '/content/drive/MyDrive/Facultad/Soporte/Proyecto_Reciclaje/modelo_trashnet_grupo6.keras'

# Le decimos a TensorFlow que lo levante
modelo_final = tf.keras.models.load_model(ruta_guardado)

print("¡El cerebro de ayer se despertó impecable! Ya sabe clasificar.")

import tensorflow as tf
from tensorflow.keras import layers, models

# 1. PEGUEN SU RUTA ACÁ ADENTRO DE LAS COMILLAS
ruta_dataset = '/content/drive/MyDrive/Facultad/Soporte/Proyecto_Reciclaje/dataset-resized'

# 2. Re-armamos las cintas transportadoras por las dudas
dataset_entrenamiento = tf.keras.utils.image_dataset_from_directory(
    ruta_dataset, validation_split=0.2, subset="training", seed=123, image_size=(224, 224), batch_size=32
)
dataset_validacion = tf.keras.utils.image_dataset_from_directory(
    ruta_dataset, validation_split=0.2, subset="validation", seed=123, image_size=(224, 224), batch_size=32
)

# 3. LA MAGIA: Creamos la capa que gira, zoomea y deforma las fotos
aumento_datos = tf.keras.Sequential([
  layers.RandomFlip("horizontal_and_vertical"),
  layers.RandomRotation(0.2),
  layers.RandomZoom(0.1),
])

# 4. Traemos el modelo base de Google (MobileNetV2) y lo congelamos
preprocesamiento = tf.keras.applications.mobilenet_v2.preprocess_input
modelo_base = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights='imagenet')
modelo_base.trainable = False

# 5. Armamos el cerebro uniendo las piezas (¡ACÁ ESTÁ EL ERROR CORREGIDO!)
entradas = tf.keras.Input(shape=(224, 224, 3))
x = aumento_datos(entradas)
x = preprocesamiento(x)
x = modelo_base(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.2)(x) # <--- LE FALTABA ESTE (x) AL FINAL
salidas = layers.Dense(6, activation='softmax')(x)

modelo_rústico = models.Model(entradas, salidas)

# 6. Compilamos
modelo_rústico.compile(optimizer='adam', loss=tf.keras.losses.SparseCategoricalCrossentropy(), metrics=['accuracy'])

# 7. ¡A transpirar! Arrancamos el entrenamiento de 15 épocas
print("\n¡Arrancando el entrenamiento rústico! A prepararse unos buenos mates que esto lleva un ratito...")
historial_rustico = modelo_rústico.fit(
    dataset_entrenamiento,
    validation_data=dataset_validacion,
    epochs=15
)

print("\n¡Listo el modelo mejorado!")